### ISSUE TITLE
update for newer versions of matlab

### ISSUE THREAD

**Issue by Scubatuba99** [kaizhang/RFECS#1]
I only have access to matlab 2017b, and when I run rfecs I get the error:

Undefined function or variable 'matlabpool'.

I checked around and the error is that matlabpool is no longer the name for the parallel processing tool. The fix is to replace "matlabpool" with "parpool" everywhere in your code.

Could you update or pull to generate a rfecs version that can run with this version of matlab? Thanks!

**Comment by kaizhang** [comment]
Hi, I'm not the author nor the maintainer of the RFECS software. I've used the RFECS software in my past research and I found that the original software is hard to use. So I wrote a wrapper and wanted to share it with anyone who is interested in using the original RFECS code. But I don't have the bandwidth to provide any updates to this software. If you have a fix, a pull request is welcome!

**Comment by kaizhang** [comment]
Fix in #4
