### ISSUE TITLE
Building from Source - Data constructor not in scope

### ISSUE THREAD

**Issue by joshcutts** [kaizhang/RFECS#2]
I'm trying to build from source as I couldn't get the binary to run on my Mac (10.13.6) but when I use cabal build I get the following errors:

`$ cabal build
Preprocessing executable 'rfecs' for RFECS-0.1.0..
Building executable 'rfecs' for RFECS-0.1.0..
[3 of 5] Compiling Paths_RFECS      ( dist/build/rfecs/autogen/Paths_RFECS.hs, dist/build/rfecs/rfecs-tmp/Paths_RFECS.o )
[4 of 5] Compiling RFECS.Utils      ( src/RFECS/Utils.hs, dist/build/rfecs/rfecs-tmp/RFECS/Utils.o )

src/RFECS/Utils.hs:38:10: error:
    Data constructor not in scope:
      BED3 :: B.ByteString -> Int -> Int -> BED3
   |
38 |     in ( BED3 (xs !! 0) (readInt $ xs !! 1) (readInt $ xs !! 2)
   |          ^^^^

src/RFECS/Utils.hs:39:10: error:
    Data constructor not in scope:
      BED3 :: B.ByteString -> Int -> Int -> BED3
   |
39 |        , BED3 (xs !! 3) (readInt $ xs !! 4) (readInt $ xs !! 5)
   |          ^^^^

`

This is my first attempt at building from source code so I might be missing something obvious. I did a fresh install of stack and cabal. Then used cabal configure in the unzipped version of the source code I downloaded.

Is there an adjustment to the source code I should make or should I be building from the source code differently?

**Comment by kaizhang** [comment]
You'd better use stack to install the software as the cabal will pick up the latest packages but many of them are not compatible with the current codes. Try:

```
stack install
```

**Comment by joshcutts** [comment]
Thanks!
