### ISSUE TITLE
Running the wrapper - bed.gz files?

### ISSUE THREAD

**Issue by joshcutts** [kaizhang/RFECS#3]
Thanks so much for writing this wrapper. Thanks to your previous help I've got everything successfully installed and can run the example that you included for chr 21.

At this point I'm just a little confused on how to get things running with my files. I see that you included a couple of gzipped bed files and it looks like your wrapper will create the input files (3 columns with counts  from these bed files? (I see this file in the output along with the enhancer predictions) I just want to ask what exactly are these bed files? Are these peak files? Or bam alignment files that have been converted to bed? Would it be possible to use bam files directly?

Thanks!

**Comment by kaizhang** [comment]
The bed files should contain aligned tags. You can get them from bam files using bedtools. It's currently not possible to use bam files directly.

**Comment by joshcutts** [comment]
Thanks so much I really appreciate it! Just one more question - does the
wrapper take care of the RPKM normalization or is that something I should
be taking care of in generation of the bed files?

**Comment by kaizhang** [comment]
It takes care of the normalization. You just need to provide the aligned tags.
