### ISSUE TITLE
Some problems about the examples

### ISSUE THREAD

**Issue by goes0n** [kaizhang/RFECS#5]
Thanks so much for writing this wrapper. I have finished a test on chr 21 and get the final file "enhancer.txt". But when I try to run it on all, which means "--chrom all", I got the error as follows:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/39076695/156721591-139eb11c-1db3-4b28-bdf4-880f7cada8f7.png">
Then, I try to run it on other single chr, such as  "--chrom chr22". I got the same error.

I'd like to know why this happened and can you please give some other examples?

Thanks!

**Comment by kaizhang** [comment]
I'm not sure as I haven't touched it for years. Would that be because the input doesn't contain other chromosomes? Maybe you can try a full dataset.

**Comment by goes0n** [comment]
ahaha I think I made a stupid mistake, ignoring the "input.yaml" .
Thank you again for your patience!  :)
